version: '3'
services:
  jenkins:
    image: jenkins/jenkins:alpine
    ports:
      - "5050:8080"
      - "50000:50000"
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
    networks:
      - demo
  hygieia:
    image: hygieiadoc/hygieia-starter-kit:latest
    depends_on:
      - jenkins
    links:
      - jenkins
    ports:
      - "80:80"
      - "27017:27017"
      - "8080:8080"
    environment:
      - PROXY_URL=
      - PROXY_PORT=
      - PROXY_USERNAME=
      - PROXY_PASSWORD=
      - GITHUB_HOST=github.com
      - GITHUB_CRON=0/60 * * * * *
      - GITHUB_PERSONAL_ACCESS_TOKEN=
      - JENKINS_CRON=0/60 * * * * *
      - JENKINS_SERVER= http://admin:admin@jenkins:8080/
      - SONAR_CRON=0/60 * * * * *
      - SONAR_HOST=
      - SONAR_VERSION=6.7
      - SONAR_METRICS=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details
      - SONAR_USERNAME=
      - SONAR_PASSWORD=
    privileged: true
    volumes:
      - ${HYGIEIA_LOGS}:/hygieia/logs
      - ${HYGIEIA_DB_DATA}:/var/lib/mongo
    networks:
      - demo
networks:
  demo:
    driver: "bridge"
